### ISSUE TITLE
Why pandas DataFrame.query wasn't used for queries in nodes_population.ids?

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/snap#125]
I've created the issue for that so this info can be used and referenced later. I mean this `query` method
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html.

**Comment by tomdele** [comment]
I was not there when all the initial design has been made. But what I can say is:
The query syntax should be as close as possible to the nodeset format.

This query syntax is also very specific for dataframes and having a query syntax "à la pandas" for libsonata (or other tools in C++ for example) would be very complex to implement imao.
For us in bluepysnap, it means we will need to create a converter from nodeset-like queries to pandas queries. This is doable but we should be very careful if we choose this path.

**Comment by asanin-epfl** [comment]
Thank you! It's good to have arguments written.
