### ISSUE TITLE
KeyError: 'node_types_file'

### ISSUE THREAD

**Issue by antonelepfl** [BlueBrain/snap#141]
I was trying to read this circuit config using Snap (0.12.1)
https://bbpcode.epfl.ch/browse/code/common/circuit-documentation/tree/source/usecases/usecase1/circuit_sonata.json?h=refs/heads/master

I got some KeyErrors and at the end I had to add the following keys
```
{
    "components": {
        "morphologies_dir": "..."
    },
    "networks": {
        "nodes": [
            {
               ....
                "node_types_file": null
            }
        ],
        "edges": [
            {
               ...
                "edge_types_file": null
            }
        ]
    }
}
```

After these additions, I did not have any other issue.

**Comment by antonelepfl** [comment]
FYI: @mgeplf

**Comment by asanin-epfl** [comment]
The keys you have added are required keys for SONATA circuits. How you didn't have those keys initially?

**Comment by mgeplf** [comment]
> How you didn't have those keys initially? 

I suspect we weren't adding them when creating circuits - that's evolved over time.

I will look into it.

**Comment by asanin-epfl** [comment]
Actually I see that there are some outdated circuits in the repo that @antonelepfl mentioned. I will update them.
