### ISSUE TITLE
Add API to get h5py Dataset view into contents of sonata files

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/snap#162]
I have come across several use cases where I need 'direct' access to the h5py version of the SONATA edges file (for instance), so that I can do chunked access to large files (ex: brainbuilder sonata split circuit).

*Perhaps* we should consider adding this; however, I'm not sure what the potential is for misuse is, and I'm not sure it's a good idea to encourage direct access.

**Comment by joni-herttuainen** [comment]
I see. If we only allow read access with a context manager, I don't think there's harm.
e.g., something like:
in edges.py
```python
@contextmanager
def access_h5(self):
    with h5py.File(self.h5_filepath, 'r') as h5:
        yield h5
```
could work. The user could then just use:
```python
with edge_pop.access_h5() as h5:
    pass  # whatever the user wants to do
```
what do you think?

**Comment by mgeplf** [comment]
I want to give it some more thought; I'm still trying to decide what to do in libsonata for a related case, and I'm still a little uncomfortable making it 'easy' to get to something that should be behind an API.  I get the feeling that the library isn't doing its job in that case.

**Comment by joni-herttuainen** [comment]
I see your point. What exactly is your use case here? You want to access to certain chunk of edge population's edge's at a time?

**Comment by mgeplf** [comment]
I'm going to close this for now, and can reopen it if it comes up again.
