### ISSUE TITLE
Performance issues when accessing `positions` for large node populations

### ISSUE THREAD

**Issue by matz-e** [BlueBrain/snap#195]
While investigating a performance bottleneck transforming morphologies of a circuit, we came across the following part of the code:

https://github.com/BlueBrain/snap/blob/839c910eac56e21f2e09850fba47d4febadcbbde/bluepysnap/morph.py#L97-L98

Accessing the `positions` function in this snipped takes a very long time. Constructing a minimal reproducer:
```
import bluepysnap as snappy
Node = snappy.sonata_constants.Node
import random
import sys
import time

pth = "/gpfs/bbp.cscs.ch/project/proj134/scratch/zisis/connectome-manipulator/circuit/circuit_config.json"
crc = snappy.circuit.Circuit(pth)
nodes = crc.nodes["root__neurons"]
node_ids = [random.randrange(nodes.size) for _ in range(100)]

if sys.argv[1:]:
    ts = time.time()
    for nid in node_ids:
        nodes.get(nid, Node.X)
        nodes.get(nid, Node.Y)
        nodes.get(nid, Node.Z)
    print("single", time.time() - ts)
else:
    ts = time.time()
    for nid in node_ids:
        nodes.positions(nid)
    print("joined", time.time() - ts)
```
And running it:
```
❯ python test.py
joined 152.9171633720398

❯ python test.py 123
single 9.43373441696167
```

Looking through the code for `positions`, it seems that we first construct a new dataframe with the required properties and selecting afterwards? Would be great if this could be switched around.

**Comment by mgeplf** [comment]
Thanks for the nice repro, I will have a look.

**Comment by mgeplf** [comment]
@matz-e can you try https://github.com/BlueBrain/snap/pull/196/ and see if it helps?

**Comment by matz-e** [comment]
I ran this with our test case, and we get some nice improvement all over the place with a total of ~30% runtime improvement! (even better than my "fix" above)
