### ISSUE TITLE
circ_extr.nodes.property_dtypes throws BluepySnapError: Same property with different dtype. model_template: category!= category

### ISSUE THREAD

**Issue by markovg** [BlueBrain/snap#198]
Hi,
I got the Zenodo SSCx anatomy Circuit object to create, 
See: https://github.com/BlueBrain/snap/issues/197

but now I'm trying to run the first query command in the example notebook, and 
'circ_extr.nodes.property_dtypes' throws a BluepySnapError: Same property with different dtype. model_template: category!= category
'circ_extr.nodes.property_names'  seems to work fine.

**Comment by markovg** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/427643/235688105-90d7c2c2-b715-44ff-90d7-d951d454821e.png)

**Comment by markovg** [comment]
This is blocking this line from running:
![image](https://user-images.githubusercontent.com/427643/235688390-ef8214f5-381a-4b0d-93b9-bc018f6eb2f6.png)

**Comment by markovg** [comment]
Apparently it calls "property_dtypes" under the hood

**Comment by markovg** [comment]
Here a deeper look at the issue:
![image](https://user-images.githubusercontent.com/427643/235717716-110508e1-2cc2-47d1-9cf0-ae4b778eda7c.png)

**Comment by markovg** [comment]
It looks to be a mismatch between the CategoricalDType of "S1nonbarrel_neurons" population and the other pops with respect to the "model_template" element.  They are all CategoricalDTypes, but with different categories (empty, or non-empty).  Should it just ignore the contents, or merge, or what? How is this used down stream?  In any case, it looks like _update would need additional logic to handle CategoricalDType?

**Comment by joni-herttuainen** [comment]
Hi @markovg,

Thank you for reporting the issue.  Unfortunately, this is a known issue that we are currently trying to find the best solution to (see: #186).

For now, if you know which population you are dealing with, I suggest you specify that when getting the nodes:
```python
data = circuit.nodes['<population_name>'].get(...)
```
or, if you need to combine data from multiple populations, iterate over the populations:
```python
data = [node_pop.get(...) for node_pop in circuit.nodes.values()] #list of dataframes, needs to be merged
```

**Comment by markovg** [comment]
The issue is arising for the example notebook for the SSCx circuit on Zenodo:
https://zenodo.org/record/6906785/files/Circuit%20exploration%20examples.ipynb?download=1

Pretty much the first line:
`lst_properties = ['layer', 'region', 'synapse_class', 'population',
                  'orientation_x', 'orientation_y', 'orientation_z', 'orientation_w',
                  'morph_class', 'model_type', 'mtype', 'morphology',
                  'x', 'y', 'z']
n_props = circ_extr.nodes.get(properties=lst_properties)`

So from your answer, I conclude this idiom is currently broken, and I should rather just deal with the  'S1nonbarrel_neurons' population on its own, correct?

**Comment by joni-herttuainen** [comment]
I should suppose replacing the line with
```python
n_props = circ_extr.nodes["S1nonbarrel_neurons"].get(properties=lst_properties)
```
would get you forward.

**Comment by markovg** [comment]
Well, but that appears to break indexing of the properties by ("pop_name", id), on which the rest of the example relies on, and which is a nice feature actually. 

But my lst_properties excludes "model_template", so this should be excluded when building the network level merged property_dtypes, thus solving the issue.  Just add a "filter" optional arguement to property_dtypes of the NetworkObject that excludes those not in the list (pass it lst_properties) ... and then there is not need to merge.  Or alternatively just drop those dtypes that are not mergeable with a 1-time warning for each one dropped. i.e.   don't throw the "same property with different type" error, rather just emit a warning that it was dropped.

**Comment by joni-herttuainen** [comment]
Yeah, I was about to edit the last comment on another changes that need to be made but you beat me to it.

>Just add a "filter" optional arguement to property_dtypes of the NetworkObject that excludes those not in the list (pass it lst_properties) ... and then there is not need to merge.  Or alternatively just drop those dtypes that are not mergeable with a 1-time warning for each one dropped.

Those are also viable options that we could consider. Thanks for the input.
