### ISSUE TITLE
regex defined node set not working in NodePopulations that don't have the property used

### ISSUE THREAD

**Issue by MWolfR** [BlueBrain/snap#204]
Situation:
A node set is defined using a regex:
```
"mc2_Column": {
    "region": {
      "$regex": "mc2.*"
    }
  }
```
The user uses the node set with a NodePopulation:
`circ.nodes["some_population"].get("mc2_Column")`
where "some_population" does _not_ have the property "region".

Expected behavior:
An empty DataFrame is returned.

Actual behavior: 
`BluepySnapError: Unknown node properties: {'region'}`

I think it is a legitimate use case to evaluate a node set against a specific NodePopulation. As such, the user should be able to expect a result and not an error.

**Comment by mgeplf** [comment]
> An empty DataFrame is returned.

That would make sense to me too; can you check if the 
```
circ.nodes["some_population"].ids("mc2_Column", raise_missing_property=False)
```
Works how you expect it to? We could potentially add the same argument to the `get()` method.

**Comment by mgeplf** [comment]
@MWolfR Just FYI, this hasn't been forgotten; we're looking at good solutions.
