### ISSUE TITLE
Filter by node or edge population `type`

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/snap#228]
When getting node and edge populations, it should be able possible to filter by `type` (as defined in the config file);
ie: `get all virtual edge populations`, or `only in non-virtual node populations`.
The idea would be that this could happen across the API.

**Comment by mgeplf** [comment]
Suggested by @MWolfR; please add more if you wish.

**Comment by joni-herttuainen** [comment]
It just about dawned on me that this is already (kind of) possible with nodes:

in h5 we have the mandatory [`model_type`](https://sonata-extension.readthedocs.io/en/latest/sonata_tech.html#fields-for-nodes) field which should conform to whatever you'd put in the Circuit Config.

Using this, we can retrieve all the certain types:
```python
circuit.nodes.get({"model_type": "virtual"}
```
or the inverse of that with a "very clear" and "self-explanatory" negative lookahead regex:
```python
circuit.nodes.get({"model_type": {"$regex": "^((?!virtual).*)$"}}))
```
this only applies to nodes, though, as edges don't have `model_type`.
