### ISSUE TITLE
parsing synapse_replay spike files as well

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/snap#230]
Hi, in addition to the spike file listed in `output/spikes_file`, there are also spike files in the `synapse_replay/spike_file`.
https://sonata-extension.readthedocs.io/en/latest/sonata_simulation.html#synapse-replay-spikes

E.g. simulation_config.json

```json
    "inputs": {
        "ABC_spikes": {
            "source": "Thalamocortical_ABC_Source",
            "node_set": "L4_PC",
            "input_type": "spikes",
            "delay": 0.0,
            "duration": 2000.0,
            "module": "synapse_replay",
            "spike_file": "PATH_TO_SPIKE_FILE/vpm_input.dat"
            },
```

I am using snap to access `output/spikes_file`, I have to use libsonata however to access `synapse_replay/spike_file`. It would be great to be able to access both spike files using the same layer (without mixing libsonata and snap).

**Comment by anilbey** [comment]
cc @andrisecker

**Comment by joni-herttuainen** [comment]
I see. These are, indeed missing from SNAP.  We'll need to see about the implementation. What would be the intended use case? Analysis of the file contents?

**Comment by anilbey** [comment]
Yes one use case can be the analysis of file contents. Another is the use of those spikes in a single cell simulation via bluecellulab.

**Comment by joni-herttuainen** [comment]
So I take it that similar interface that we have for `output/spikes_file` would suffice, right?

**Comment by anilbey** [comment]
Yes that would be ideal.
