### ISSUE TITLE
invalid syntax at bluepysnap/_version.py

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/snap#234]
Hi, with `bluepysnap==1.0.7` we started having the following error

```shell
File "/cells/e-model-packages/.tox/py3-sscx/lib/python3.9/site-packages/bluepysnap/_version.py", line 4
E       __version__ : str = version : str = '1.0.7'
E                                   ^
E   SyntaxError: invalid syntax
```

Here is the full log: https://bbpgitlab.epfl.ch/cells/e-model-packages/-/jobs/911346

**Comment by mgeplf** [comment]
setuptools_scm had to yank a release, I assume b/c of this:
https://pypi.org/project/setuptools-scm/8.0.0/

**Comment by mgeplf** [comment]
https://github.com/pypa/setuptools_scm/commit/6a80dbb87fb6dfdb167b32f3f2728ba1d196bf8f

**Comment by anilbey** [comment]
Ah yes. Thanks, ok then it'll be automatically solved :)

**Comment by joni-herttuainen** [comment]
yeah, they released a new version so this will require no action
