### ISSUE TITLE
Convergence and Divergence statistics

### ISSUE THREAD

**Issue by ThibLY** [BlueBrain/snap#236]
Hi,

Would it be possible to implement a method such as the Bluepy `circuit.stats.sample_convergence` and `circuit.stats.sample_divergence` to analyze the model connectivity please?
This is a very useful feature in Bluepy and it would be nice to have it in snap.

Thank you in advance for your time.
Best regards,
Thibaud L'Yvonnet

**Comment by mgeplf** [comment]
That sounds like it should be possible; @joni-herttuainen can you have a look?
