### ISSUE TITLE
need to check if a node population is biophysical before instantiate morph

### ISSUE THREAD

**Issue by tomdele** [BlueBrain/snap#66]
We do not have any checks for the model_type before instantiating the MorphHelper . 
We need to throw if not `biophysical`

**Comment by asanin-epfl** [comment]
FYI #27

**Comment by tomdele** [comment]
You were actually in the future @asanin-epfl !!! 
I can't compete ...

**Comment by tomdele** [comment]
thx for pointing this I totally forgot about it ...
