### ISSUE TITLE
circuit validation : Should remove the `components` from the mandatory keys if virtual nodes only

### ISSUE THREAD

**Issue by tomdele** [BlueBrain/snap#84]
The `components` key is not mandatory in the very specific usecase of virtual neurons only circuit. We should have errors only if the circuit contains neuron types that need extra files. 
Nothing prevents us from having a simple graph with no bio/single segment/point neurons in the circuit.

**Comment by tomdele** [comment]
@asanin-epfl if you have time for this let me know.

**Comment by asanin-epfl** [comment]
ok, I will look

**Comment by tomdele** [comment]
no worries, nothing urgent.

**Comment by asanin-epfl** [comment]
good. The correct way would be to drop the requirements for those fields at all and check for them only when we stumble upon the first biophysical node.

**Comment by tomdele** [comment]
yes indeed.

**Comment by asanin-epfl** [comment]
#86
