### ISSUE TITLE
Get Circuit Targets

### ISSUE THREAD

**Issue by antonelepfl** [BlueBrain/snap#87]
I was having a look at the [Node properties notebook](https://github.com/BlueBrain/snap/blob/master/doc/source/notebooks/03_node_properties.ipynb)

And in Cell 6 I see that to obtain the targets you do `node_population.node_sets` but in my case if I do it I get:
```AttributeError: 'NodePopulation' object has no attribute 'node_sets'```

But if I do it directly on the circuit as `list(circuit.node_sets)` I get the information.

Should we update the documentation?

**Comment by tomdele** [comment]
Thanks you are indeed right. 
I changed this some sometimes ago and did not revisited the examples. 

You indeed need to access the node_sets via the circuit interface.

**Comment by tomdele** [comment]
I will change the example.
