### ISSUE TITLE
Deprecation warning collections

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/snap#89]
Just letting you know that my tests get a deprecation warning:
bluepysnap/nodes.py:421: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working

**Comment by mgeplf** [comment]
Thanks; @tomdele will have a look when he's back.

**Comment by tomdele** [comment]
Forgot to close this issue.
This have been solved in the #109
